name: cf-gnnexplainer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - matplotlib=3.3.*
  - pytorch_geometric=1.6.*
  - tqdm=4.50.*
  - typing=3.10.0.*
  - typing_extensions=3.10.0.*
  - typing_inspect=0.6.*
  - networkx=2.5.*
  - numpy=1.19.*
  - numpy-base=1.19.*
  - pandas=1.1.*
